version: '3.9'

volumes:
  mongos-router-data:
  mongo-config-server-1-data:
  mongo-config-server-2-data:
  mongo-config-server-3-data:
  mongo-shard1-rs1-data:
  mongo-shard1-rs2-data:
  mongo-shard1-rs3-data:
  mongo-shard2-rs1-data:
  mongo-shard2-rs2-data:
  mongo-shard2-rs3-data:
  mongo-shard3-rs1-data:
  mongo-shard3-rs2-data:
  mongo-shard3-rs3-data:

services:
  # ==============================================
  #                    Роутер
  # ==============================================
  mongos-router:
    image: mongo:7
    container_name: mongos-router
    hostname: mongos-router
    volumes:
      - mongos-router-data:/data/db
      - ./mongodb-keyfile:/etc/mongo-keyfile:ro
    depends_on:
      - mongo-config-server-1
      - mongo-config-server-2
      - mongo-config-server-3
    command: mongos --configdb config-rs/mongo-config-server-1:20001,mongo-config-server-2:20002,mongo-config-server-3:20003 --bind_ip_all --keyFile /etc/mongo-keyfile
    ports:
      - "10001:27017"

  # ==============================================
  #              Config Servers (3 ноды)
  # ==============================================

  mongo-config-server-1:
    image: mongo:7
    container_name: mongo-config-server-1
    hostname: mongo-config-server-1
    volumes:
      - mongo-config-server-1-data:/data/db
      - ./mongodb-keyfile:/etc/mongo-keyfile:ro
    command: [ "bash", "-c", "
        mongod --configsvr --replSet config-rs --bind_ip_all --port 20001 --dbpath /data/db --keyFile /etc/mongo-keyfile --auth &
        sleep 10 &&
        mongosh --port 20001 --eval '
          try {
            rs.initiate({
                _id: \"config-rs\",
                configsvr: true,
                members: [
                  { _id: 0, host: \"mongo-config-server-1:20001\" },
                  { _id: 1, host: \"mongo-config-server-2:20002\" },
                  { _id: 2, host: \"mongo-config-server-3:20003\" }
                ]
              });
          } catch(e) {}' &&
        wait
      " ]
    ports:
      - "20001:20001"

  mongo-config-server-2:
    image: mongo:7
    container_name: mongo-config-server-2
    hostname: mongo-config-server-2
    volumes:
      - mongo-config-server-2-data:/data/db
      - ./mongodb-keyfile:/etc/mongo-keyfile:ro
    command: ["--configsvr", "--replSet", "config-rs", "--bind_ip_all", "--port", "20002", "--keyFile", "/etc/mongo-keyfile", "--auth"]
    ports:
      - "20002:20002"

  mongo-config-server-3:
    image: mongo:7
    container_name: mongo-config-server-3
    hostname: mongo-config-server-3
    volumes:
      - mongo-config-server-3-data:/data/db
      - ./mongodb-keyfile:/etc/mongo-keyfile:ro
    command: ["--configsvr", "--replSet", "config-rs", "--bind_ip_all", "--port", "20003", "--keyFile", "/etc/mongo-keyfile", "--auth"]
    ports:
      - "20003:20003"

  # ==============================================
  #                  Первый шард
  # ==============================================
  mongo-shard1-rs1:
    image: mongo:7
    container_name: mongo-shard1-rs1
    hostname: mongo-shard1-rs1
    volumes:
      - mongo-shard1-rs1-data:/data/db
      - ./mongodb-keyfile:/etc/mongo-keyfile:ro
    command: [ "bash", "-c", "
        mongod --shardsvr --replSet shard1-rs --bind_ip_all --port 30001 --dbpath /data/db --keyFile /etc/mongo-keyfile --auth &
        sleep 10 &&
        mongosh --port 30001 --eval '
          try {
            rs.initiate({
                _id: \"shard1-rs\",
                members: [
                  { _id: 0, host: \"mongo-shard1-rs1:30001\" },
                  { _id: 1, host: \"mongo-shard1-rs2:30002\" },
                  { _id: 2, host: \"mongo-shard1-rs3:30003\" }
                ]
              });
          } catch(e) {}' &&
        wait
      " ]
    ports:
      - "30001:30001"

  mongo-shard1-rs2:
    image: mongo:7
    container_name: mongo-shard1-rs2
    hostname: mongo-shard1-rs2
    volumes:
      - mongo-shard1-rs2-data:/data/db
      - ./mongodb-keyfile:/etc/mongo-keyfile:ro
    command: ["--shardsvr", "--replSet", "shard1-rs", "--bind_ip_all", "--port", "30002", "--keyFile", "/etc/mongo-keyfile", "--auth"]
    ports:
      - "30002:30002"

  mongo-shard1-rs3:
    image: mongo:7
    container_name: mongo-shard1-rs3
    hostname: mongo-shard1-rs3
    volumes:
      - mongo-shard1-rs3-data:/data/db
      - ./mongodb-keyfile:/etc/mongo-keyfile:ro
    command: ["--shardsvr", "--replSet", "shard1-rs", "--bind_ip_all", "--port", "30003", "--keyFile", "/etc/mongo-keyfile", "--auth"]
    ports:
      - "30003:30003"

  # ==============================================
  #                  Второй шард
  # ==============================================
  mongo-shard2-rs1:
    image: mongo:7
    container_name: mongo-shard2-rs1
    hostname: mongo-shard2-rs1
    volumes:
      - mongo-shard2-rs1-data:/data/db
      - ./mongodb-keyfile:/etc/mongo-keyfile:ro
    command: [ "bash", "-c", "
        mongod --shardsvr --replSet shard2-rs --bind_ip_all --port 40001 --dbpath /data/db --keyFile /etc/mongo-keyfile --auth &
        sleep 10 &&
        mongosh --port 40001 --eval '
          try {
            rs.initiate({
                _id: \"shard2-rs\",
                members: [
                  { _id: 0, host: \"mongo-shard2-rs1:40001\" },
                  { _id: 1, host: \"mongo-shard2-rs2:40002\" },
                  { _id: 2, host: \"mongo-shard2-rs3:40003\" }
                ]
              });
          } catch(e) {}' &&
        wait
      " ]
    ports:
      - "40001:40001"

  mongo-shard2-rs2:
    image: mongo:7
    container_name: mongo-shard2-rs2
    hostname: mongo-shard2-rs2
    volumes:
      - mongo-shard2-rs2-data:/data/db
      - ./mongodb-keyfile:/etc/mongo-keyfile:ro
    command: ["--shardsvr", "--replSet", "shard2-rs", "--bind_ip_all", "--port", "40002", "--keyFile", "/etc/mongo-keyfile", "--auth"]
    ports:
      - "40002:40002"

  mongo-shard2-rs3:
    image: mongo:7
    container_name: mongo-shard2-rs3
    hostname: mongo-shard2-rs3
    volumes:
      - mongo-shard2-rs3-data:/data/db
      - ./mongodb-keyfile:/etc/mongo-keyfile:ro
    command: ["--shardsvr", "--replSet", "shard2-rs", "--bind_ip_all", "--port", "40003", "--keyFile", "/etc/mongo-keyfile", "--auth"]
    ports:
      - "40003:40003"

  # ==============================================
  #                  Третий шард
  # ==============================================
  mongo-shard3-rs1:
    image: mongo:7
    container_name: mongo-shard3-rs1
    hostname: mongo-shard3-rs1
    volumes:
      - mongo-shard3-rs1-data:/data/db
      - ./mongodb-keyfile:/etc/mongo-keyfile:ro
    command: [ "bash", "-c", "
        mongod --shardsvr --replSet shard3-rs --bind_ip_all --port 50001 --dbpath /data/db --keyFile /etc/mongo-keyfile --auth &
        sleep 10 &&
        mongosh --port 50001 --eval '
          try {
            rs.initiate({
                _id: \"shard3-rs\",
                members: [
                  { _id: 0, host: \"mongo-shard3-rs1:50001\" },
                  { _id: 1, host: \"mongo-shard3-rs2:50002\" },
                  { _id: 2, host: \"mongo-shard3-rs3:50003\" }
                ]
              });
          } catch(e) {}' &&
        wait
      " ]
    ports:
      - "50001:50001"

  mongo-shard3-rs2:
    image: mongo:7
    container_name: mongo-shard3-rs2
    hostname: mongo-shard3-rs2
    volumes:
      - mongo-shard3-rs2-data:/data/db
      - ./mongodb-keyfile:/etc/mongo-keyfile:ro
    command: ["--shardsvr", "--replSet", "shard3-rs", "--bind_ip_all", "--port", "50002", "--keyFile", "/etc/mongo-keyfile", "--auth"]
    ports:
      - "50002:50002"

  mongo-shard3-rs3:
    image: mongo:7
    container_name: mongo-shard3-rs3
    hostname: mongo-shard3-rs3
    volumes:
      - mongo-shard3-rs3-data:/data/db
      - ./mongodb-keyfile:/etc/mongo-keyfile:ro
    command: ["--shardsvr", "--replSet", "shard3-rs", "--bind_ip_all", "--port", "50003", "--keyFile", "/etc/mongo-keyfile", "--auth"]
    ports:
      - "50003:50003"