up-rs:
	docker-compose -f ./docker-compose.yml up -d

down-rs:
	docker-compose -f ./docker-compose.yml down

restart-rs:
	docker-compose -f ./docker-compose.yml down
	docker-compose -f ./docker-compose.yml up -d